name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ['hyperenv', 'medium']
    strategy:
      matrix:
        node: ['14', '16', '17']

    name: Node.js ${{ matrix.node }}

    steps:

    - uses: 'actions/checkout@v2'

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: npm

    - name: install dependencies
      run: npm ci

    - name: run tests
      run: npm test
